# Generated by Django 5.1 on 2024-09-06 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_servicio', models.CharField(max_length=1000, verbose_name='Opinion del servicio')),
                ('tipo_solicitud', models.CharField(choices=[('', 'Seleccione su solicitud'), ('p', 'Pregunta'), ('q', 'Queja'), ('r', 'Reclamo'), ('s', 'Sugerencia'), ('f', 'Felicitacion')], max_length=1, verbose_name='Tipo de solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
