# Generated by Django 5.1 on 2024-09-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Apellido')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('puntos_ganados', models.IntegerField(default=0, verbose_name='Puntos Ganados')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('foto_perfil', models.ImageField(blank=True, max_length=200, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2, verbose_name='Tipo de Identificación')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
