# Generated by Django 5.1 on 2024-09-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Usuarios/fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('', 'Seleccione su identificación'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2, verbose_name='Tipo de Identificación'),
        ),
    ]
