# Generated by Django 5.1 on 2024-09-06 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_album', models.CharField(default='JetBoom', max_length=50)),
                ('descripcion', models.TextField(default='Este es tú album de fotos, dónde podras almacenar todas mis historias. ¡Disfrútalo!', max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='Usuarios/fotos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario_publico', models.CharField(blank=True, max_length=500)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.albumfoto')),
            ],
        ),
    ]
